"""add import_tasks table

Revision ID: 9dba554eadfe
Revises: a3f7c9d21e45
Create Date: 2026-04-01 22:34:01.509144

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9dba554eadfe'
down_revision: Union[str, Sequence[str], None] = 'a3f7c9d21e45'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('import_tasks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='pending', nullable=False),
    sa.Column('recipe_id', sa.Uuid(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], name='fk_import_tasks_recipe_id'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_import_tasks_user_id'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_import_tasks_user_id'), 'import_tasks', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_import_tasks_user_id'), table_name='import_tasks')
    op.drop_table('import_tasks')
    # ### end Alembic commands ###
